// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateEventInput struct {
	Title       string    `json:"title"`
	Description *string   `json:"description,omitempty"`
	Capacity    int       `json:"capacity"`
	StartsAt    time.Time `json:"startsAt"`
	EndsAt      time.Time `json:"endsAt"`
}

type CreateSessionInput struct {
	EventID     string    `json:"eventId"`
	Title       string    `json:"title"`
	Description *string   `json:"description,omitempty"`
	StartsAt    time.Time `json:"startsAt"`
	EndsAt      time.Time `json:"endsAt"`
	Room        *string   `json:"room,omitempty"`
}

type CreateSpeakerInput struct {
	FullName  string  `json:"fullName"`
	Bio       *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type Event struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description,omitempty"`
	Status      EventStatus `json:"status"`
	Capacity    int         `json:"capacity"`
	StartsAt    time.Time   `json:"startsAt"`
	EndsAt      time.Time   `json:"endsAt"`
}

type EventFilterInput struct {
	Status *EventStatus `json:"status,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RegistrationTicket struct {
	ID          string             `json:"id"`
	EventID     string             `json:"eventId"`
	UserID      string             `json:"userId"`
	Status      RegistrationStatus `json:"status"`
	QRCodeValue string             `json:"qrCodeValue"`
	CheckedInAt *time.Time         `json:"checkedInAt,omitempty"`
}

type Session struct {
	ID          string     `json:"id"`
	EventID     string     `json:"eventId"`
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	StartsAt    time.Time  `json:"startsAt"`
	EndsAt      time.Time  `json:"endsAt"`
	Room        *string    `json:"room,omitempty"`
	Speakers    []*Speaker `json:"speakers"`
}

type Speaker struct {
	ID        string  `json:"id"`
	FullName  string  `json:"fullName"`
	Bio       *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type SpeakerFilterInput struct {
	Query *string `json:"query,omitempty"`
}

type UpdateEventInput struct {
	ID          string     `json:"id"`
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	Capacity    *int       `json:"capacity,omitempty"`
	StartsAt    *time.Time `json:"startsAt,omitempty"`
	EndsAt      *time.Time `json:"endsAt,omitempty"`
}

type UpdateMyProfileInput struct {
	DisplayName string `json:"displayName"`
}

type UpdateSessionInput struct {
	ID          string     `json:"id"`
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	StartsAt    *time.Time `json:"startsAt,omitempty"`
	EndsAt      *time.Time `json:"endsAt,omitempty"`
	Room        *string    `json:"room,omitempty"`
}

type UpdateSpeakerInput struct {
	ID        string  `json:"id"`
	FullName  *string `json:"fullName,omitempty"`
	Bio       *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	Role        Role   `json:"role"`
}

type EventStatus string

const (
	EventStatusDraft     EventStatus = "draft"
	EventStatusPublished EventStatus = "published"
	EventStatusCancelled EventStatus = "cancelled"
)

var AllEventStatus = []EventStatus{
	EventStatusDraft,
	EventStatusPublished,
	EventStatusCancelled,
}

func (e EventStatus) IsValid() bool {
	switch e {
	case EventStatusDraft, EventStatusPublished, EventStatusCancelled:
		return true
	}
	return false
}

func (e EventStatus) String() string {
	return string(e)
}

func (e *EventStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventStatus", str)
	}
	return nil
}

func (e EventStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RegistrationStatus string

const (
	RegistrationStatusActive    RegistrationStatus = "active"
	RegistrationStatusCancelled RegistrationStatus = "cancelled"
)

var AllRegistrationStatus = []RegistrationStatus{
	RegistrationStatusActive,
	RegistrationStatusCancelled,
}

func (e RegistrationStatus) IsValid() bool {
	switch e {
	case RegistrationStatusActive, RegistrationStatusCancelled:
		return true
	}
	return false
}

func (e RegistrationStatus) String() string {
	return string(e)
}

func (e *RegistrationStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RegistrationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RegistrationStatus", str)
	}
	return nil
}

func (e RegistrationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleMember     Role = "member"
	RoleTeamMember Role = "team_member"
	RoleOrganizer  Role = "organizer"
	RoleSuperAdmin Role = "super_admin"
)

var AllRole = []Role{
	RoleMember,
	RoleTeamMember,
	RoleOrganizer,
	RoleSuperAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleMember, RoleTeamMember, RoleOrganizer, RoleSuperAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
